### ISSUE TITLE
Error in maya 2016 when checking scale

### ISSUE THREAD

**Issue by sbourgoing** [sbourgoing/omtk#1]
classModule line #517

inn.getMatrix(worldSpace=True).scale doesn't work in maya 2016

# Traceback (most recent call last):
#   File "C:/Users/emorin/Documents/GitHub/omtk/python\omtk\core\classRig.py", line 757, in build
#     module.build(**kwargs)
#   File "C:\Users\emorin\Documents\GitHub\omtk\python\omtk\modules\rigFK.py", line 82, in build
#     super(FK, self).build(create_grp_rig=create_grp_rig, *args, **kwargs)
#   File "C:/Users/emorin/Documents/GitHub/omtk/python\omtk\core\classModule.py", line 517, in build
#     if not inn.getMatrix(worldSpace=True).scale.isEquivalent(pymel.dt.Vector([1.0, 1.0, 1.0]).get()):
#   File "C:\Program Files\Autodesk\Maya2016\Python\lib\site-packages\pymel\internal\factories.py", line 2550, in __getattribute__
#     return super(newcls, self).__getattribute__(name)
#   File "C:\Program Files\Autodesk\Maya2016\Python\lib\site-packages\pymel\core\datatypes.py", line 1665, in _getScale
#     t.getScale(p, _api.MSpace.kTransform)
# TypeError: getScale() takes exactly 2 arguments (3 given)

**Comment by sbourgoing** [comment]
Probably related to maya 2016 not having the latest service pack
